### PR TITLE
BUG: fix wrong variable name in call to dwt_axis

### PR DESCRIPTION
**Pull request by grlee77**

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
Merged the first. Going to look at the second in a bit more detail, I think your proposal makes a copy even if the dtype is already correct, so this would not be necessary.

**Comment by grlee77** [comment]
yes.  I think `np.asarray` should only copy if necessary.  For `np.array`, the copy=False flag could be used.  Having said that, I did see a minor performance decrease after adding those checks.

The two issues in the tests that those fixed were:
1.) allow integer inputs in some of the tests to pass
2.) the tests expect a ValueError if an invalid type such as a dict is passed in.  np.array was raising this ValueError.  If np.ndarray is specified in the dwtn function signature, a TypeError is raised instead which seems reasonable as well, but would require changing the test.

**Comment by kwohlfahrt** [comment]
Just re-opened this to keep track and discuss things.

1) That is true. I'd like to keep everything cdef'd in dwt_axis, so I've written a slightly different `checkDtype` function that does this correctly. It needs merging with the other before this goes to `master`
2) I think any array-like should be accepted, e.g. lists, so `np.asarray` is the correct option. However, we should raise a `TypeError` if it is not a numeric type, as the message about 1D inputs is confusing if e.g. a dict was passed.

**Comment by kwohlfahrt** [comment]
The PR on pywavelets is open, so closing here.

**Pull request closed without merging**
